In [1]:
# TODO

In [1]:
# Sauthoff2023_outlines collates Antarctic active subglacial lakes from past inventories (Smith and others, 2009; Siegfried & Fricker, 2018)
# as well as point data of lakes in the latest inventor (Livingstone and others, 2022) as well as individual studies since.
#
# Written 2023-01-17 by W. Sauthoff (sauthoff@mines.edu)

# Import internal packages
import os

# Import external packages
from shapely.geometry import Point
# from shapely import Point
from pyproj import CRS, Transformer

# define data and script directories dependent on home environment
if os.getenv('HOME') == '/home/jovyan':
    DATA_DIR = '/home/jovyan/data_dir'
    SCRIPT_DIR = '/home/jovyan/script_dir'
elif os.getenv('HOME') == '/Users/Wilson': 
    DATA_DIR = '/Volumes/ExtremeSSD/data'
    SCRIPT_DIR = '/Users/Wilson/Documents/0-code/repos_my/script_dir'

# define utility functions
def ll2ps(lon, lat):
    """
    Transform coordinates from geodetic coordinates (lon, lat)
    to Antarctic Polar Stereograph coordinates (x, y)
    x, y = ll2ps(lon, lat)
    """
    crs_ll = CRS("EPSG:4326")
    crs_xy = CRS("EPSG:3031")
    ll_to_xy = Transformer.from_crs(crs_ll, crs_xy, always_xy = True)
    x, y = ll_to_xy.transform(lon, lat)
    return x, y

def ps2ll(x, y):
    """
    Transform coordinates from Antarctic Polar Stereograph
    to geodetic (lon, lat) coordinates
    
    lon, lat = ps2ll(x, y)
    """
    crs_ll = CRS("EPSG:4326")
    crs_xy = CRS("EPSG:3031")
    xy_to_ll = Transformer.from_crs(crs_xy, crs_ll, always_xy = True)
    lon, lat = xy_to_ll.transform(x, y)
    return lon, lat

In [2]:
# import most recent inventory of subglacial lake outlines 
outlines = open(SCRIPT_DIR + '/SiegfriedFricker2018_outlines.py')
read_file = outlines.read()
exec(read_file)

# display dataframe preview
SiegfriedFricker2018_outlines

,name,geometry,area (m^2),perimeter (m),cite
0,Bindschadler_1,"POLYGON ((-792264.327 -691480.857, -791281.458...",1.943146e+08,51147.562479,"Smith and others, 2009, J. Glac., doi:10.3189/..."
1,Bindschadler_2,"POLYGON ((-842788.063 -708464.240, -842354.948...",1.072249e+08,37249.152584,"Smith and others, 2009, J. Glac., doi:10.3189/..."
2,Bindschadler_3,"POLYGON ((-874893.221 -654533.044, -876415.673...",1.404559e+08,44183.483257,"Smith and others, 2009, J. Glac., doi:10.3189/..."
3,Bindschadler_4,"POLYGON ((-828821.778 -584874.415, -828822.032...",2.816411e+08,62680.016773,"Smith and others, 2009, J. Glac., doi:10.3189/..."
4,Bindschadler_5,"POLYGON ((-858067.460 -573467.564, -858714.391...",3.923966e+08,73686.203194,"Smith and others, 2009, J. Glac., doi:10.3189/..."
...,...,...,...,...,...
126,Whillans_6,"POLYGON ((-451544.869 -488823.261, -451209.964...",7.458477e+07,31952.842516,"Smith and others, 2009, J. Glac., doi:10.3189/..."
127,Whillans_7,"POLYGON ((-543163.376 -500759.165, -542800.367...",7.696570e+07,32373.996995,"Smith and others, 2009, J. Glac., doi:10.3189/..."
128,Whillans_8,"POLYGON ((-654478.748 -281124.560, -653777.327...",1.625714e+08,45873.974279,"Smith and others, 2009, J. Glac., doi:10.3189/..."
129,Wilkes_1,"POLYGON ((2214185.180 -666018.604, 2214317.389...",5.880773e+08,89565.314574,"Smith and others, 2009, J. Glac., doi:10.3189/..."
130,Wilkes_2,"POLYGON ((1985649.483 -1222665.850, 1986964.16...",1.766583e+08,48307.837257,"Smith and others, 2009, J. Glac., doi:10.3189/..."

In [36]:
# Read in spreadsheet using pandas read_excel
url = 'https://static-content.springer.com/esm/art%3A10.1038%2Fs43017-021-00246-9/MediaObjects/43017_2021_246_MOESM1_ESM.xlsx'
use_cols = ['Name', 'Lat.  oN', 'Lon. oE', 'Lake Type', 'References', 'Prior Inventory']
import_rows = np.arange(0,676)
Livingstone2022_points = pd.read_excel(url, sheet_name='Antarctica', usecols=use_cols, skiprows = lambda x: x not in import_rows)

# View just the active lakes of the pandas dataset
Livingstone2022_points_activelakes = Livingstone2022_points[Livingstone2022_points['Lake Type'] == 'Active']
Livingstone2022_points_activelakes = Livingstone2022_points_activelakes.reset_index(drop=True)
Livingstone2022_points_activelakes

,Name,Lat. oN,Lon. oE,Lake Type,References,Prior Inventory
0,Bindschadler5,-80.610,-123.994,Active,Gray et al. (2005); Smith et al. (2009),Wright & Siegert (2012)
1,Kamb10,-81.446,-120.134,Active,Gray et al. (2005); Smith et al. (2009),Wright & Siegert (2012)
2,L1,-74.000,133.270,Active,Wingham et al. (2006); Surveyed by ICECAP in 2...,Wright & Siegert (2012)
3,U1,-75.940,135.000,Active,Wingham et al. (2006),Wright & Siegert (2012)
4,U2,-76.340,135.770,Active,Wingham et al. (2006),Wright & Siegert (2012)
...,...,...,...,...,...,...
134,THW142,-76.618,-106.185,Active,Smith et al. (2017); Hoffman et al. (2020); Ma...,NaN
135,THW124,-76.462,-106.893,Active,Smith et al. (2017) and Hoffman et al. (2020).,NaN
136,THW70,-75.990,-107.023,Active,Smith et al. (2017) and Hoffman et al. (2020).,NaN
137,WT,-77.300,-114.000,Active,Hoffman et al. (2020).,NaN
138,HG,-75.900,-111.000,Active,Hoffman et al. (2020).,NaN

In [14]:
Livingstone2022_points_activelakes_new = Livingstone2022_points_activelakes.copy(deep=True)
Livingstone2022_points_activelakes_new.drop(Livingstone2022_points_activelakes_new.loc[Livingstone2022_points_activelakes['References'].str.contains('Smith et al.|Siegfried & Fricker')].index, inplace=True)
Livingstone2022_points_activelakes_new = Livingstone2022_points_activelakes_new.reset_index(drop=True)
print(len(Livingstone2022_points_activelakes_new))
Livingstone2022_points_activelakes_new

11

,Name,Lat. oN,Lon. oE,Lake Type,References,Prior Inventory
0,L1,-74.000,133.270,Active,Wingham et al. (2006); Surveyed by ICECAP in 2...,Wright & Siegert (2012)
1,U1,-75.940,135.000,Active,Wingham et al. (2006),Wright & Siegert (2012)
2,U2,-76.340,135.770,Active,Wingham et al. (2006),Wright & Siegert (2012)
3,U3,-76.680,135.930,Active,Wingham et al. (2006),Wright & Siegert (2012)
4,Byrd1 (DL),-81.026,148.302,Active,"Stearns et al., (2008)",Wright & Siegert (2012)
5,Byrd2 (UL),-80.684,146.887,Active,"Stearns et al., (2008)",Wright & Siegert (2012)
6,“Site A”,-67.800,112.540,Active,N. Young (personal comm.),Wright & Siegert (2012)
7,“Site B”,-67.870,113.530,Active,N. Young (personal comm.),Wright & Siegert (2012)
8,“Site C”,-67.840,114.040,Active,N. Young (personal comm.),Wright & Siegert (2012)
9,WT,-77.300,-114.000,Active,Hoffman et al. (2020).,NaN
10,HG,-75.900,-111.000,Active,Hoffman et al. (2020).,NaN

In [37]:
Livingstone2022_points_activelakes_new = Livingstone2022_points_activelakes.copy(deep=True)
Livingstone2022_points_activelakes_new.drop(Livingstone2022_points_activelakes_new.loc[Livingstone2022_points_activelakes['References'].str.contains('Smith et al. (2009)', regex=False)].index, inplace=True)
Livingstone2022_points_activelakes_new = Livingstone2022_points_activelakes_new.reset_index(drop=True)
print(len(Livingstone2022_points_activelakes_new))
Livingstone2022_points_activelakes_new

25

,Name,Lat. oN,Lon. oE,Lake Type,References,Prior Inventory
0,L1,-74.000,133.270,Active,Wingham et al. (2006); Surveyed by ICECAP in 2...,Wright & Siegert (2012)
1,U1,-75.940,135.000,Active,Wingham et al. (2006),Wright & Siegert (2012)
2,U2,-76.340,135.770,Active,Wingham et al. (2006),Wright & Siegert (2012)
3,U3,-76.680,135.930,Active,Wingham et al. (2006),Wright & Siegert (2012)
4,PPT-16 (Lake Mercer) (Mercer2),-84.661,-149.677,Active,"Fricker et al. (2007), Blankenship et al. (200...",Wright & Siegert (2012)
5,Mercer1,-84.602,-154.191,Active,Fricker et al. (2007); Siegfried et al. (2014)...,Wright & Siegert (2012)
6,Whillans1 (Lake Engelhardt),-83.731,-157.419,Active,"Lake Engelhardt (Fricker et al., 2007); Carter...",Wright & Siegert (2012)
7,Whillans2a (L12),-84.035,-160.271,Active,Fricker et al. (2007); Siegfried & Fricker (2018),Wright & Siegert (2012)
8,Whillans2b (L10),-84.343,-158.196,Active,Fricker et al. (2007); Siegfried & Fricker (2018),Wright & Siegert (2012)
9,Whillans3 (Whillans Subglacial Lale),-84.240,-153.694,Active,"Lake Whillans, (Fricker et al., 2007); Geophys...",Wright & Siegert (2012)
10,Whillans4 (Lake Conway),-84.374,-148.719,Active,"Lake Conway (Fricker et al., 2007); Carter et ...",Wright & Siegert (2012)
11,Byrd1 (DL),-81.026,148.302,Active,"Stearns et al., (2008)",Wright & Siegert (2012)
12,Byrd2 (UL),-80.684,146.887,Active,"Stearns et al., (2008)",Wright & Siegert (2012)
13,Mac3,-80.017,-142.813,Active,Fricker et al. (2010); Siegfried & Fricker (20...,Wright & Siegert (2012)
14,“Site A”,-67.800,112.540,Active,N. Young (personal comm.),Wright & Siegert (2012)
15,“Site B”,-67.870,113.530,Active,N. Young (personal comm.),Wright & Siegert (2012)
16,“Site C”,-67.840,114.040,Active,N. Young (personal comm.),Wright & Siegert (2012)
17,KT2,-82.321,-148.018,Active,Kim et al. (2016); Siegfried & Fricker (2018),NaN
18,KT3,-82.471,-150.587,Active,Kim et al. (2016); Siegfried & Fricker (2018),NaN
19,THW170,-76.868,-106.000,Active,Smith et al. (2017); Hoffman et al. (2020); Ma...,NaN
20,THW142,-76.618,-106.185,Active,Smith et al. (2017); Hoffman et al. (2020); Ma...,NaN
21,THW124,-76.462,-106.893,Active,Smith et al. (2017) and Hoffman et al. (2020).,NaN
22,THW70,-75.990,-107.023,Active,Smith et al. (2017) and Hoffman et al. (2020).,NaN
23,WT,-77.300,-114.000,Active,Hoffman et al. (2020).,NaN
24,HG,-75.900,-111.000,Active,Hoffman et al. (2020).,NaN

In [35]:
Livingstone2022_points_activelakes_new.drop(Livingstone2022_points_activelakes_new.loc[Livingstone2022_points_activelakes['References'].str.contains('Siegfried & Fricker (2018)', regex=False)].index, inplace=True)
Livingstone2022_points_activelakes_new = Livingstone2022_points_activelakes_new.reset_index(drop=True)
print(len(Livingstone2022_points_activelakes_new))
Livingstone2022_points_activelakes_new

7

,Name,Lat. oN,Lon. oE,Lake Type,References,Prior Inventory
0,L1,-74.000,133.270,Active,Wingham et al. (2006); Surveyed by ICECAP in 2...,Wright & Siegert (2012)
1,U1,-75.940,135.000,Active,Wingham et al. (2006),Wright & Siegert (2012)
2,Mac3,-80.017,-142.813,Active,Fricker et al. (2010); Siegfried & Fricker (20...,Wright & Siegert (2012)
3,“Site A”,-67.800,112.540,Active,N. Young (personal comm.),Wright & Siegert (2012)
4,“Site B”,-67.870,113.530,Active,N. Young (personal comm.),Wright & Siegert (2012)
5,“Site C”,-67.840,114.040,Active,N. Young (personal comm.),Wright & Siegert (2012)
6,HG,-75.900,-111.000,Active,Hoffman et al. (2020).,NaN

In [34]:
Livingstone2022_points_activelakes_new.drop(Livingstone2022_points_activelakes_new.loc[Livingstone2022_points_activelakes['References'].str.contains('Smith et al. (2017) and Hoffman et al. (2020).', regex=False)].index, inplace=True)
Livingstone2022_points_activelakes_new = Livingstone2022_points_activelakes_new.reset_index(drop=True)
print(len(Livingstone2022_points_activelakes_new))
Livingstone2022_points_activelakes_new

14

,Name,Lat. oN,Lon. oE,Lake Type,References,Prior Inventory
0,L1,-74.000,133.270,Active,Wingham et al. (2006); Surveyed by ICECAP in 2...,Wright & Siegert (2012)
1,U1,-75.940,135.000,Active,Wingham et al. (2006),Wright & Siegert (2012)
2,Mac3,-80.017,-142.813,Active,Fricker et al. (2010); Siegfried & Fricker (20...,Wright & Siegert (2012)
3,“Site A”,-67.800,112.540,Active,N. Young (personal comm.),Wright & Siegert (2012)
4,“Site B”,-67.870,113.530,Active,N. Young (personal comm.),Wright & Siegert (2012)
5,“Site C”,-67.840,114.040,Active,N. Young (personal comm.),Wright & Siegert (2012)
6,KT2,-82.321,-148.018,Active,Kim et al. (2016); Siegfried & Fricker (2018),NaN
7,KT3,-82.471,-150.587,Active,Kim et al. (2016); Siegfried & Fricker (2018),NaN
8,THW170,-76.868,-106.000,Active,Smith et al. (2017); Hoffman et al. (2020); Ma...,NaN
9,THW142,-76.618,-106.185,Active,Smith et al. (2017); Hoffman et al. (2020); Ma...,NaN
10,THW124,-76.462,-106.893,Active,Smith et al. (2017) and Hoffman et al. (2020).,NaN
11,THW70,-75.990,-107.023,Active,Smith et al. (2017) and Hoffman et al. (2020).,NaN
12,WT,-77.300,-114.000,Active,Hoffman et al. (2020).,NaN
13,HG,-75.900,-111.000,Active,Hoffman et al. (2020).,NaN

In [5]:
SiegfriedFricker2018_outlines['cite'].unique()

array(['Smith and others, 2009, J. Glac., doi:10.3189/002214309789470879',
       'Fricker & Scambos, 2009, J. Glac., doi:10.3189/002214309788608813',
       'McMillan and others, 2013, GRL, doi:10.1002/grl.50689',
       'Kim and others, 2016, TC, doi:10.5194/tc-10-2971-2016',
       'Carter and others, 2013, J. Glac., doi:10.3189/2013JoG13J085',
       'Fricker and others, 2010, J. Glac., doi:10.3189/002214310791968557',
       'Fricker and others, 2014, J. Glac., doi:10.3189/2014JoG14J063',
       'Siegfried & Fricker, 2018, Ann. Glac., doi:10.1017/aog.2017.36',
       'Smith and others, 2017, TC, doi:10.5194/tc-11-451-2017'],
      dtype=object)

In [6]:
for idx in range(len(SiegfriedFricker2018_outlines['cite'].unique())): 
    length = len(SiegfriedFricker2018_outlines[SiegfriedFricker2018_outlines['cite'].str.contains(SiegfriedFricker2018_outlines['cite'].unique()[idx])])
    print(SiegfriedFricker2018_outlines['cite'].unique()[idx])
    print(length)

Smith and others, 2009, J. Glac., doi:10.3189/002214309789470879
97
Fricker & Scambos, 2009, J. Glac., doi:10.3189/002214309788608813
7
McMillan and others, 2013, GRL, doi:10.1002/grl.50689
1
Kim and others, 2016, TC, doi:10.5194/tc-10-2971-2016
3
Carter and others, 2013, J. Glac., doi:10.3189/2013JoG13J085
1
Fricker and others, 2010, J. Glac., doi:10.3189/002214310791968557
8
Fricker and others, 2014, J. Glac., doi:10.3189/2014JoG14J063
9
Siegfried & Fricker, 2018, Ann. Glac., doi:10.1017/aog.2017.36
1
Smith and others, 2017, TC, doi:10.5194/tc-11-451-2017
4

In [8]:
for idx in range(len(Livingstone2022_points_activelakes['References'].unique())): 
    length = len(Livingstone2022_points_activelakes[Livingstone2022_points_activelakes['References'].str.contains(Livingstone2022_points_activelakes['References'].unique()[idx], regex=False)])
    print(Livingstone2022_points_activelakes['References'].unique()[idx])
    print(length)

Gray et al. (2005); Smith et al. (2009)
2
Wingham et al. (2006); Surveyed by ICECAP in 2008/09 (Wright et al., 2012)
1
Wingham et al. (2006)
4
Fricker et al. (2007), Blankenship et al. (2009), Siegfried et al., (2014), Siegfried & Fricker (2018)
1
Fricker et al. (2007); Siegfried et al. (2014); Siegfried & Fricker (2018)
1
Lake Engelhardt (Fricker et al., 2007); Carter et al., (2013); Siegfried & Fricker (2018)
1
Fricker et al. (2007); Siegfried & Fricker (2018)
2
Lake Whillans, (Fricker et al., 2007); Geophysical observations made at low stand (Christianson et al., 2012 and Horgan et al. 2012); Carter et al., (2013); Siegfried et al. (2014); Siegfried & Fricker (2018).
1
Lake Conway (Fricker et al., 2007); Carter et al., (2013); Siegfried et al. (2014); Siegfried & Fricker (2018)
1
Stearns et al., (2008)
2
Smith et al. (2009)
114
Smith et al. (2009); (Welch et al., 2009)
1
Smith et al. (2009); McMillan et al., (2013); Flament et al. (2014); Li et al., (2020)
1
Smith et al. (2009); Siegfried & Fricker (2018)
9
Smith et al. (2009). Kim et al. (2016); Siegfried & Fricker (2018)
1
Smith et al. (2009). Kim et al. (2016)
3
Smith et al. (2009); Kim et al. (2016)
1
Smith et al. (2009), Mac1 in Fricker et al. (2010); Siegfried & Fricker (2018)
1
Smith et al. (2009), Mac2 in Fricker et al. (2010); Siegfried & Fricker (2018)
1
Smith et al. (2009); Wright et al., (2012); Siegfried & Fricker (2018)
1
Smith et al. (2009); Carter et al., (2013); Siegfried & Fricker (2018)
3
Fricker et al. (2010); Siegfried & Fricker (2018).
1
Fricker et al. (2010), part of MacAyeal3 in Smith et al. (2009)
2
N. Young (personal comm.)
3
Kim et al. (2016); Siegfried & Fricker (2018)
3
Smith et al. (2017); Hoffman et al. (2020); Malczyk et al. (2020)
2
Smith et al. (2017); Hoffman et al. (2020); Malczyk et al. (2020).
1
Smith et al. (2017) and Hoffman et al. (2020).
2
Hoffman et al. (2020).
4

In [39]:
Livingstone2022_points_activelakes.loc[Livingstone2022_points_activelakes['References'].str.contains('Smith et al. (2009)', regex=False)]

,Name,Lat. oN,Lon. oE,Lake Type,References,Prior Inventory
0,Bindschadler5,-80.610,-123.994,Active,Gray et al. (2005); Smith et al. (2009),Wright & Siegert (2012)
1,Kamb10,-81.446,-120.134,Active,Gray et al. (2005); Smith et al. (2009),Wright & Siegert (2012)
15,Academy1 (Foundation 1),-84.135,-61.337,Active,Smith et al. (2009),Smith et al. (2009) / Wright & Siegert (2012)
16,Academy2 (Foundation 2),-84.536,-57.445,Active,Smith et al. (2009),Smith et al. (2009) / Wright & Siegert (2012)
17,Academy3 (Foundation3),-84.608,-59.082,Active,Smith et al. (2009),Smith et al. (2009) / Wright & Siegert (2012)
...,...,...,...,...,...,...
122,Whillans8,-83.504,-113.601,Active,Smith et al. (2009),Smith et al. (2009) / Wright & Siegert (2012)
123,Wilkes1,-68.812,106.715,Active,Smith et al. (2009); Siegfried & Fricker (2018),Smith et al. (2009) / Wright & Siegert (2012)
124,Wilkes2,-68.703,121.566,Active,Smith et al. (2009),Smith et al. (2009) / Wright & Siegert (2012)
126,Mac4,-79.736,-139.000,Active,"Fricker et al. (2010), part of MacAyeal3 in Sm...",Wright & Siegert (2012)
127,Mac5,-79.636,-139.109,Active,"Fricker et al. (2010), part of MacAyeal3 in Sm...",Wright & Siegert (2012)

In [42]:
SiegfriedFricker2018_outlines['name'].tolist()

['Bindschadler_1',
 'Bindschadler_2',
 'Bindschadler_3',
 'Bindschadler_4',
 'Bindschadler_5',
 'Bindschadler_6',
 'Byrd_1',
 'Byrd_2',
 'Byrd_s1',
 'Byrd_s10',
 'Byrd_s11',
 'Byrd_s12',
 'Byrd_s13',
 'Byrd_s14',
 'Byrd_s15',
 'Byrd_s2',
 'Byrd_s3',
 'Byrd_s4',
 'Byrd_s5',
 'Byrd_s6',
 'Byrd_s7',
 'Byrd_s8',
 'Byrd_s9',
 'ConwaySubglacialLake',
 'Cook_E1',
 'Cook_E2',
 'David_1',
 'David_s1',
 'David_s2',
 'David_s3',
 'David_s4',
 'David_s5',
 'EAP_1',
 'EAP_2',
 'EAP_3',
 'EAP_4',
 'EAP_5',
 'EAP_6',
 'EAP_7',
 'EAP_8',
 'EAP_9',
 'EngelhardtSubglacialLake',
 'Foundation_1',
 'Foundation_10',
 'Foundation_11',
 'Foundation_12',
 'Foundation_13',
 'Foundation_14',
 'Foundation_15',
 'Foundation_16',
 'Foundation_2',
 'Foundation_3',
 'Foundation_4',
 'Foundation_5',
 'Foundation_6',
 'Foundation_7',
 'Foundation_8',
 'Foundation_9',
 'Foundation_N1',
 'Foundation_N2',
 'Foundation_N3',
 'Institute_E1',
 'Institute_E2',
 'Institute_W1',
 'Institute_W2',
 'KT1',
 'KT2',
 'KT3',
 'Kamb_1',
 'Kamb_10',
 'Kamb_11',
 'Kamb_12',
 'Kamb_2',
 'Kamb_3',
 'Kamb_4',
 'Kamb_5',
 'Kamb_6',
 'Kamb_7',
 'Kamb_8',
 'Kamb_9',
 'Lake10',
 'Lake12',
 'Lake78',
 'Lambert_1',
 'LennoxKing_1',
 'Mac1',
 'Mac2',
 'Mac3',
 'Mac4',
 'Mac5',
 'Mac6',
 'Mac7',
 'Mac8',
 'MercerSubglacialLake',
 'Mertz_1',
 'Mulock_1',
 'Nimrod_1',
 'Nimrod_2',
 'Ninnis_1',
 'Ninnis_2',
 'Raymond_1',
 'Rec1',
 'Rec10',
 'Rec2',
 'Rec3',
 'Rec4',
 'Rec5',
 'Rec6',
 'Rec8',
 'Rec9',
 'Rutford_1',
 'Slessor_1',
 'Slessor_23',
 'Slessor_4',
 'Slessor_5',
 'Slessor_6',
 'Slessor_7',
 'Thw_124',
 'Thw_142',
 'Thw_170',
 'Thw_70',
 'Totten_1',
 'Totten_2',
 'UpperSubglacialLakeConway',
 'Vostok_1',
 'WhillansSubglacialLake',
 'Whillans_6',
 'Whillans_7',
 'Whillans_8',
 'Wilkes_1',
 'Wilkes_2']

In [15]:
# copy geopandas dataframe to begin making edits
Sauthoff2023_outlines = SiegfriedFricker2018_outlines.copy(deep=True)

# add new column and populate with whether lake is within CryoSat-2 (CS2) InSAR coverage
Sauthoff2023_outlines['CS2_InSAR'] = np.where(Sauthoff2023_outlines['name'].isin(CS2InSAR_lakes),'True', 'False')

# display dataframe preview
Sauthoff2023_outlines

,name,geometry,area (m^2),perimeter (m),cite,CS2_InSAR
0,Bindschadler_1,"POLYGON ((-792264.327 -691480.857, -791281.458...",1.943146e+08,51147.562479,"Smith and others, 2009, J. Glac., doi:10.3189/...",False
1,Bindschadler_2,"POLYGON ((-842788.063 -708464.240, -842354.948...",1.072249e+08,37249.152584,"Smith and others, 2009, J. Glac., doi:10.3189/...",False
2,Bindschadler_3,"POLYGON ((-874893.221 -654533.044, -876415.673...",1.404559e+08,44183.483257,"Smith and others, 2009, J. Glac., doi:10.3189/...",False
3,Bindschadler_4,"POLYGON ((-828821.778 -584874.415, -828822.032...",2.816411e+08,62680.016773,"Smith and others, 2009, J. Glac., doi:10.3189/...",False
4,Bindschadler_5,"POLYGON ((-858067.460 -573467.564, -858714.391...",3.923966e+08,73686.203194,"Smith and others, 2009, J. Glac., doi:10.3189/...",False
...,...,...,...,...,...,...
126,Whillans_6,"POLYGON ((-451544.869 -488823.261, -451209.964...",7.458477e+07,31952.842516,"Smith and others, 2009, J. Glac., doi:10.3189/...",True
127,Whillans_7,"POLYGON ((-543163.376 -500759.165, -542800.367...",7.696570e+07,32373.996995,"Smith and others, 2009, J. Glac., doi:10.3189/...",True
128,Whillans_8,"POLYGON ((-654478.748 -281124.560, -653777.327...",1.625714e+08,45873.974279,"Smith and others, 2009, J. Glac., doi:10.3189/...",False
129,Wilkes_1,"POLYGON ((2214185.180 -666018.604, 2214317.389...",5.880773e+08,89565.314574,"Smith and others, 2009, J. Glac., doi:10.3189/...",False
130,Wilkes_2,"POLYGON ((1985649.483 -1222665.850, 1986964.16...",1.766583e+08,48307.837257,"Smith and others, 2009, J. Glac., doi:10.3189/...",False

In [ ]:
# find polar stereographic x, y for western Thwaites (WT) lake centroid lon, lat in Hoffman and others, 2020, The Cryosphere approximated from fig. 1a
ll2ps(-113.82, -77.22)

In [16]:
# add rows for newer lakes from publications not included in 2018 inventory (using approx centroid point when outline not available)

# Smith 2009 Recovery_8 (dropped from SF18 outlines) to see if there's activity
Sauthoff2023_outlines.loc[len(Sauthoff2023_outlines)] = ['', '', 'nan', 'nan', '', ''] 


# Hoffman and others, 2020, The Cryosphere
# Haynes Glacier (HG) lakes
Sauthoff2023_outlines.loc[len(Sauthoff2023_outlines)] = ['TL96', Point(-1438000, -545000), 'nan', 'nan', 'Hoffman and others, 2020, Cryosphere, doi:10.5194/tc-14-4603-2020', 'True'] 
# Sauthoff2023_outlines.loc[len(Sauthoff2023_outlines)] = ['TL108', 'POINT (-1427000, -542500)', 'nan', 'nan', 'Hoffman and others, 2020, Cryosphere, doi:10.5194/tc-14-4603-2020', 'True'] 
# Sauthoff2023_outlines.loc[len(Sauthoff2023_outlines)] = ['TL115', 'POINT (-1422000, -537500)', 'nan', 'nan', 'Hoffman and others, 2020, Cryosphere, doi:10.5194/tc-14-4603-2020', 'True'] 
# Sauthoff2023_outlines.loc[len(Sauthoff2023_outlines)] = ['TL122', 'POINT (-1418000, -532500)', 'nan', 'nan', 'Hoffman and others, 2020, Cryosphere, doi:10.5194/tc-14-4603-2020', 'True'] 
# # western Thwaites (WT) lake
# Sauthoff2023_outlines.loc[len(Sauthoff2023_outlines)] = ['WT', 'POINT (-1275377, -563040)', 'nan', 'nan', 'Hoffman and others, 2020, Cryosphere, doi:10.5194/tc-14-4603-2020', 'True'] 

# # Siegfried and Fricker, 2021, Geophys. Res. Lett.
# # Lower Subglacial Lake Mercer (LSLM)
# Sauthoff2023_outlines.loc[len(Sauthoff2023_outlines)] = ['', '', 'nan', 'nan', '', ''] 
# # Lower Subglacial Lake Mercer (LSLC
# Sauthoff2023_outlines.loc[len(Sauthoff2023_outlines)] = ['', '', 'nan', 'nan', '', ''] 


# add rows for lake candidates I've observed in ICESat-2 data (using approx centroid point until outline is established)
# New observation at ~–450 km, –540 km (polar stereographic x, y)
Sauthoff2023_outlines.loc[len(Sauthoff2023_outlines)] = ['lower_Whillans6', 'POINT (-450000, -540000)', 'nan', 'nan', 'Sauthoff and others, in prep', 'True'] 

# display dataframe preview
Sauthoff2023_outlines

,name,geometry,area (m^2),perimeter (m),cite,CS2_InSAR
0,Bindschadler_1,"POLYGON ((-792264.327362 -691480.857142, -7912...",194314586.957039,51147.562479,"Smith and others, 2009, J. Glac., doi:10.3189/...",False
1,Bindschadler_2,"POLYGON ((-842788.063077 -708464.24025, -84235...",107224893.755613,37249.152584,"Smith and others, 2009, J. Glac., doi:10.3189/...",False
2,Bindschadler_3,"POLYGON ((-874893.221204 -654533.044355, -8764...",140455869.623497,44183.483257,"Smith and others, 2009, J. Glac., doi:10.3189/...",False
3,Bindschadler_4,"POLYGON ((-828821.777959 -584874.414823, -8288...",281641064.156359,62680.016773,"Smith and others, 2009, J. Glac., doi:10.3189/...",False
4,Bindschadler_5,"POLYGON ((-858067.460067 -573467.563734, -8587...",392396583.575172,73686.203194,"Smith and others, 2009, J. Glac., doi:10.3189/...",False
...,...,...,...,...,...,...
127,Whillans_7,"POLYGON ((-543163.375533 -500759.16526, -54280...",76965701.866243,32373.996995,"Smith and others, 2009, J. Glac., doi:10.3189/...",True
128,Whillans_8,"POLYGON ((-654478.748309 -281124.560477, -6537...",162571436.702585,45873.974279,"Smith and others, 2009, J. Glac., doi:10.3189/...",False
129,Wilkes_1,"POLYGON ((2214185.18045 -666018.604064, 221431...",588077293.262162,89565.314574,"Smith and others, 2009, J. Glac., doi:10.3189/...",False
130,Wilkes_2,"POLYGON ((1985649.48349 -1222665.85001, 198696...",176658323.865225,48307.837257,"Smith and others, 2009, J. Glac., doi:10.3189/...",False
131,TL96,"POINT (-1438000, -545000)",nan,nan,"Hoffman and others, 2020, Cryosphere, doi:10.5...",True